// ignore_for_file: unused_import

import 'package:uzima/core/const/path_constants.dart';
import 'package:uzima/core/const/text_constants.dart';
import 'package:uzima/data/exercise_data.dart';
import 'package:uzima/data/workout_data.dart';
import 'package:uzima/screens/onboarding/widget/onboarding_tile.dart';

class DataConstants {
  // Onboarding
  static final onboardingTiles = [
    const OnboardingTile(
        title: TextConstants.onboarding1Title,
        mainText: TextConstants.onboarding1Description,
        imagePath: PathConstants.onboarding1),
    const OnboardingTile(
      title: TextConstants.onboarding2Title,
      mainText: TextConstants.onboarding2Description,
      imagePath: PathConstants.onboarding2,
    ),
    const OnboardingTile(
      title: TextConstants.onboarding3Title,
      mainText: TextConstants.onboarding3Description,
      imagePath: PathConstants.onboarding3,
    )
  ];

  // Workouts

  // Workouts
  static final List<WorkoutData> workouts = [
    WorkoutData(
      id: 'workout1',
      title: TextConstants.yogaTitle,
      exercises: TextConstants.yogaExercises,
      minutes: TextConstants.yogaMinutes,
      currentProgress: 0,
      progress: 6,
      image: PathConstants.yoga,
      exerciseDataList: [
        ExerciseData(
          id: 'exercise1',
          title: TextConstants.reclining,
          minutes: TextConstants.recliningMinutes,
          progress: 0,
          video: PathConstants.recliningVideo,
          description: TextConstants.warriorDescription,
          steps: [
            TextConstants.warriorStep1,
            TextConstants.warriorStep2,
            TextConstants.warriorStep1,
            TextConstants.warriorStep2,
            TextConstants.warriorStep1,
            TextConstants.warriorStep2,
          ],
        ),
        ExerciseData(
          id: 'exercise2',
          title: TextConstants.cowPose,
          minutes: TextConstants.cowPoseMinutes,
          progress: 0,
          video: PathConstants.cowPoseVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise3',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise4',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise5',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise6',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
      ],
    ),
    WorkoutData(
      id: 'workout2',
      title: TextConstants.fullBodyTitle,
      exercises: TextConstants.fullBodyExercises,
      minutes: TextConstants.fullBodyMinutes,
      currentProgress: 0,
      progress: 7,
      image: PathConstants.fullBody,
      exerciseDataList: [
        ExerciseData(
          id: 'exercise1',
          title: TextConstants.reclining,
          minutes: TextConstants.recliningMinutes,
          progress: 0.99,
          video: PathConstants.recliningVideo,
          description: TextConstants.warriorDescription,
          steps: [
            TextConstants.warriorStep1,
            TextConstants.warriorStep2,
          ],
        ),
        ExerciseData(
          id: 'exercise2',
          title: TextConstants.cowPose,
          minutes: TextConstants.cowPoseMinutes,
          progress: 0,
          video: PathConstants.cowPoseVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise3',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise4',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise5',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise6',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise7',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
      ],
    ),
    WorkoutData(
      id: 'workout3',
      title: TextConstants.upperBodyTitle,
      exercises: TextConstants.upperBodyExercises,
      minutes: TextConstants.upperBodyMinutes,
      currentProgress: 0,
      progress: 8,
      image: PathConstants.upperBody,
      exerciseDataList: [
        ExerciseData(
          id: 'exercise1',
          title: TextConstants.reclining,
          minutes: TextConstants.recliningMinutes,
          progress: 0,
          video: PathConstants.recliningVideo,
          description: TextConstants.warriorDescription,
          steps: [
            TextConstants.warriorStep1,
            TextConstants.warriorStep2,
            TextConstants.warriorStep1,
            TextConstants.warriorStep2,
            TextConstants.warriorStep1,
            TextConstants.warriorStep2,
          ],
        ),
        ExerciseData(
          id: 'exercise2',
          title: TextConstants.cowPose,
          minutes: TextConstants.cowPoseMinutes,
          progress: 0,
          video: PathConstants.cowPoseVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise3',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise4',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise5',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise6',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise7',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise8',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
      ],
    ),
    WorkoutData(
      id: 'workout4',
      title: TextConstants.lowerBodyTitle,
      exercises: TextConstants.lowerBodyExercises,
      minutes: TextConstants.lowerBodyMinutes,
      currentProgress: 0,
      progress: 8,
      image: PathConstants.lowerBody,
      exerciseDataList: [
        ExerciseData(
          id: 'exercise1',
          title: TextConstants.reclining,
          minutes: TextConstants.recliningMinutes,
          progress: 0,
          video: PathConstants.recliningVideo,
          description: TextConstants.warriorDescription,
          steps: [
            TextConstants.warriorStep1,
            TextConstants.warriorStep2,
            TextConstants.warriorStep1,
            TextConstants.warriorStep2,
            TextConstants.warriorStep1,
            TextConstants.warriorStep2,
          ],
        ),
        ExerciseData(
          id: 'exercise2',
          title: TextConstants.cowPose,
          minutes: TextConstants.cowPoseMinutes,
          progress: 0,
          video: PathConstants.cowPoseVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise3',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise4',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise5',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise3',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise6',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise7',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise8',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
      ],
    ),
    WorkoutData(
      id: 'workout5',
      title: TextConstants.abdominalTitle,
      exercises: TextConstants.abdominalExercises,
      minutes: TextConstants.abdominalMinutes,
      currentProgress: 0,
      progress: 3,
      image: PathConstants.abdominal,
      exerciseDataList: [
        ExerciseData(
          id: 'exercise1',
          title: TextConstants.reclining,
          minutes: TextConstants.recliningMinutes,
          progress: 0,
          video: PathConstants.recliningVideo,
          description: TextConstants.warriorDescription,
          steps: [
            TextConstants.warriorStep1,
            TextConstants.warriorStep2,
            TextConstants.warriorStep1,
            TextConstants.warriorStep2,
            TextConstants.warriorStep1,
            TextConstants.warriorStep2,
          ],
        ),
        ExerciseData(
          id: 'exercise2',
          title: TextConstants.cowPose,
          minutes: TextConstants.cowPoseMinutes,
          progress: 0,
          video: PathConstants.cowPoseVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise3',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
      ],
    ),
    WorkoutData(
      id: 'workout6',
      title: TextConstants.chestTitle,
      exercises: TextConstants.chestExercises,
      minutes: TextConstants.chestMinutes,
      currentProgress: 0,
      progress: 6,
      image: PathConstants.chest,
      exerciseDataList: [
        ExerciseData(
          id: 'exercise1',
          title: TextConstants.reclining,
          minutes: TextConstants.recliningMinutes,
          progress: 0,
          video: PathConstants.recliningVideo,
          description: TextConstants.warriorDescription,
          steps: [
            TextConstants.warriorStep1,
            TextConstants.warriorStep2,
            TextConstants.warriorStep1,
            TextConstants.warriorStep2,
            TextConstants.warriorStep1,
            TextConstants.warriorStep2,
          ],
        ),
        ExerciseData(
          id: 'exercise2',
          title: TextConstants.cowPose,
          minutes: TextConstants.cowPoseMinutes,
          progress: 0,
          video: PathConstants.cowPoseVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise3',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise4',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise5',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise6',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
      ],
    ),
    WorkoutData(
      id: 'workout7',
      title: TextConstants.armsTitle,
      exercises: TextConstants.armsExercises,
      minutes: TextConstants.armsMinutes,
      currentProgress: 0,
      progress: 10,
      image: PathConstants.arms,
      exerciseDataList: [
        ExerciseData(
          id: 'exercise1',
          title: TextConstants.reclining,
          minutes: TextConstants.recliningMinutes,
          progress: 0,
          video: PathConstants.recliningVideo,
          description: TextConstants.warriorDescription,
          steps: [
            TextConstants.warriorStep1,
            TextConstants.warriorStep2,
            TextConstants.warriorStep1,
            TextConstants.warriorStep2,
            TextConstants.warriorStep1,
            TextConstants.warriorStep2,
          ],
        ),
        ExerciseData(
          id: 'exercise2',
          title: TextConstants.cowPose,
          minutes: TextConstants.cowPoseMinutes,
          progress: 0,
          video: PathConstants.cowPoseVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise3',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise4',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise5',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise6',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise7',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise8',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise9',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise10',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
      ],
    ),
    WorkoutData(
      id: 'workout8',
      title: TextConstants.cardioTitle,
      exercises: TextConstants.cardioExercises,
      minutes: TextConstants.cardioMinutes,
      currentProgress: 0,
      progress: 3,
      image: PathConstants.cardio,
      exerciseDataList: [
        ExerciseData(
          id: 'exercise1',
          title: TextConstants.reclining,
          minutes: TextConstants.recliningMinutes,
          progress: 0,
          video: PathConstants.recliningVideo,
          description: TextConstants.warriorDescription,
          steps: [
            TextConstants.warriorStep1,
            TextConstants.warriorStep2,
            TextConstants.warriorStep1,
            TextConstants.warriorStep2,
            TextConstants.warriorStep1,
            TextConstants.warriorStep2,
          ],
        ),
        ExerciseData(
          id: 'exercise2',
          title: TextConstants.cowPose,
          minutes: TextConstants.cowPoseMinutes,
          progress: 0,
          video: PathConstants.cowPoseVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise3',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
      ],
    ),
    WorkoutData(
      id: 'workout9',
      title: TextConstants.stretchingTitle,
      exercises: TextConstants.stretchingExercises,
      minutes: TextConstants.stretchingMinutes,
      currentProgress: 0,
      progress: 3,
      image: PathConstants.stretching,
      exerciseDataList: [
        ExerciseData(
          id: 'exercise1',
          title: TextConstants.reclining,
          minutes: TextConstants.recliningMinutes,
          progress: 0,
          video: PathConstants.recliningVideo,
          description: TextConstants.warriorDescription,
          steps: [
            TextConstants.warriorStep1,
            TextConstants.warriorStep2,
            TextConstants.warriorStep1,
            TextConstants.warriorStep2,
            TextConstants.warriorStep1,
            TextConstants.warriorStep2,
          ],
        ),
        ExerciseData(
          id: 'exercise2',
          title: TextConstants.cowPose,
          minutes: TextConstants.cowPoseMinutes,
          progress: 0,
          video: PathConstants.cowPoseVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise3',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
      ],
    ),
    WorkoutData(
      id: 'workout10',
      title: TextConstants.pilatesTitle,
      exercises: TextConstants.pilatesExercises,
      minutes: TextConstants.pilatesMinutes,
      currentProgress: 0,
      progress: 5,
      image: PathConstants.pilates,
      exerciseDataList: [
        ExerciseData(
          id: 'exercise1',
          title: TextConstants.reclining,
          minutes: TextConstants.recliningMinutes,
          progress: 0,
          video: PathConstants.recliningVideo,
          description: TextConstants.warriorDescription,
          steps: [
            TextConstants.warriorStep1,
            TextConstants.warriorStep2,
            TextConstants.warriorStep1,
            TextConstants.warriorStep2,
            TextConstants.warriorStep1,
            TextConstants.warriorStep2,
          ],
        ),
        ExerciseData(
          id: 'exercise2',
          title: TextConstants.cowPose,
          minutes: TextConstants.cowPoseMinutes,
          progress: 0,
          video: PathConstants.cowPoseVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise3',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise4',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise5',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
      ],
    ),
    WorkoutData(
      id: 'workout11',
      title: TextConstants.loosefatTitle,
      exercises: TextConstants.loosefatExercises,
      minutes: TextConstants.loosefatMinutes,
      currentProgress: 0,
      progress: 4,
      image: PathConstants.loosefat,
      exerciseDataList: [
        ExerciseData(
          id: 'exercise1',
          title: TextConstants.reclining,
          minutes: TextConstants.recliningMinutes,
          progress: 0,
          video: PathConstants.recliningVideo,
          description: TextConstants.warriorDescription,
          steps: [
            TextConstants.warriorStep1,
            TextConstants.warriorStep2,
            TextConstants.warriorStep1,
            TextConstants.warriorStep2,
            TextConstants.warriorStep1,
            TextConstants.warriorStep2,
          ],
        ),
        ExerciseData(
          id: 'exercise2',
          title: TextConstants.cowPose,
          minutes: TextConstants.cowPoseMinutes,
          progress: 0,
          video: PathConstants.cowPoseVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise3',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise4',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
      ],
    ),
    WorkoutData(
      id: 'workout12',
      title: TextConstants.crossfitTitle,
      exercises: TextConstants.crossfitExercises,
      minutes: TextConstants.crossfitMinutes,
      currentProgress: 0,
      progress: 6,
      image: PathConstants.crossfit,
      exerciseDataList: [
        ExerciseData(
          id: 'exercise1',
          title: TextConstants.reclining,
          minutes: TextConstants.recliningMinutes,
          progress: 0,
          video: PathConstants.recliningVideo,
          description: TextConstants.warriorDescription,
          steps: [
            TextConstants.warriorStep1,
            TextConstants.warriorStep2,
            TextConstants.warriorStep1,
            TextConstants.warriorStep2,
            TextConstants.warriorStep1,
            TextConstants.warriorStep2,
          ],
        ),
        ExerciseData(
          id: 'exercise2',
          title: TextConstants.cowPose,
          minutes: TextConstants.cowPoseMinutes,
          progress: 0,
          video: PathConstants.cowPoseVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise3',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise4',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise5',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise6',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
      ],
    ),
    WorkoutData(
      id: 'workout13',
      title: TextConstants.outdoorTitle,
      exercises: TextConstants.outdoorExercises,
      minutes: TextConstants.outdoorMinutes,
      currentProgress: 0,
      progress: 7,
      image: PathConstants.outdoor,
      exerciseDataList: [
        ExerciseData(
          id: 'exercise1',
          title: TextConstants.reclining,
          minutes: TextConstants.recliningMinutes,
          progress: 0,
          video: PathConstants.recliningVideo,
          description: TextConstants.warriorDescription,
          steps: [
            TextConstants.warriorStep1,
            TextConstants.warriorStep2,
            TextConstants.warriorStep1,
            TextConstants.warriorStep2,
            TextConstants.warriorStep1,
            TextConstants.warriorStep2,
          ],
        ),
        ExerciseData(
          id: 'exercise2',
          title: TextConstants.cowPose,
          minutes: TextConstants.cowPoseMinutes,
          progress: 0,
          video: PathConstants.cowPoseVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise3',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise4',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise5',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise6',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise7',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
      ],
    ),
    WorkoutData(
      id: 'workout14',
      title: TextConstants.absTitle,
      exercises: TextConstants.absExercises,
      minutes: TextConstants.absMinutes,
      currentProgress: 0,
      progress: 3,
      image: PathConstants.abs,
      exerciseDataList: [
        ExerciseData(
          id: 'exercise1',
          title: TextConstants.reclining,
          minutes: TextConstants.recliningMinutes,
          progress: 0,
          video: PathConstants.recliningVideo,
          description: TextConstants.warriorDescription,
          steps: [
            TextConstants.warriorStep1,
            TextConstants.warriorStep2,
            TextConstants.warriorStep1,
            TextConstants.warriorStep2,
            TextConstants.warriorStep1,
            TextConstants.warriorStep2,
          ],
        ),
        ExerciseData(
          id: 'exercise2',
          title: TextConstants.cowPose,
          minutes: TextConstants.cowPoseMinutes,
          progress: 0,
          video: PathConstants.cowPoseVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise3',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
      ],
    ),
    WorkoutData(
      id: 'workout15',
      title: TextConstants.legsTitle,
      exercises: TextConstants.legsExercises,
      minutes: TextConstants.legsMinutes,
      currentProgress: 0,
      progress: 4,
      image: PathConstants.legs,
      exerciseDataList: [
        ExerciseData(
          id: 'exercise1',
          title: TextConstants.reclining,
          minutes: TextConstants.recliningMinutes,
          progress: 0,
          video: PathConstants.recliningVideo,
          description: TextConstants.warriorDescription,
          steps: [
            TextConstants.warriorStep1,
            TextConstants.warriorStep2,
            TextConstants.warriorStep1,
            TextConstants.warriorStep2,
            TextConstants.warriorStep1,
            TextConstants.warriorStep2,
          ],
        ),
        ExerciseData(
          id: 'exercise2',
          title: TextConstants.cowPose,
          minutes: TextConstants.cowPoseMinutes,
          progress: 0,
          video: PathConstants.cowPoseVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise3',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise4',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
      ],
    )
  ];

// Reminder
  static List<String> reminderDays = [
    TextConstants.everyday,
    TextConstants.monday_friday,
    TextConstants.weekends,
    TextConstants.monday,
    TextConstants.tuesday,
    TextConstants.wednesday,
    TextConstants.thursday,
    TextConstants.friday,
    TextConstants.saturday,
    TextConstants.sunday,
  ];
}
